version: "3.9"

services:
  # Main:
  #   image: nginx
  #   container_name: ${Container_Name_Prefix}-Main
  #   restart: unless-stopped
  #   ports:
  #     - "${Port_Main}:80"
  #   volumes:
  #     - ${Volumn_Main_Path}:/var/www/html
  #   # depends_on:
  #   #   - Database
  #   networks:
  #     extnet:
  #       ipv4_address: ${IPv4_Main}

  app:
    build:
      context: ./myapp
      dockerfile: Dockerfile.dev
    volumes:
      - ./myapp:/app
    ports:
      - 3000:3000
    networks:
      - mynet

  # Database:
  #   image: mysql/mysql-server:latest
  #   container_name: ${Container_Name_Prefix}-Database
  #   ports:
  #     - "${Port_Database}:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1qaz@WSX3edc
  #     MYSQL_DATABASE: testdb
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #   networks:
  #     extnet:
  #       ipv4_address: ${IPv4_Database}
  #     mynet:
  #   volumes:
  #     - ${Volumn_DB_Path}:/var/lib/mysql

  # DbManager:
  #   image: phpmyadmin:latest
  #   container_name: ${Container_Name_Prefix}-DbManager
  #   restart: unless-stopped
  #   ports:
  #     - "${Port_DbManager}:80"
  #   depends_on:
  #     - Database
  #   links:
  #     - Database
  #   environment:
  #     PMA_HOST: Database
  #     PMA_PORT: 3306
  #   networks:
  #     extnet:
  #       ipv4_address: ${IPv4_DbManager}

  # redis:
  #   image: redis:alpine
  #   command: "redis-server --requirepass ${REDIS_PASSWORD}"
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1k"
  #       max-file: "3"
  #   expose:
  #     - "${REDIS_PORT}"

  mongo:
    image: mongo
    volumes:
      #volumes對應虛擬目錄/實體目錄
      - ./mongo/config:/data/configdb
      - ./mongo/data:/data/db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      mynet:


  mongo-express:
    image: mongo-express:0.54.0 #使用docker hub映像檔案
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    networks:
      mynet:


networks:
  mynet:
